### ISSUE TITLE
Please release a new tag containing logrotate

### ISSUE THREAD

**Issue by pysan3** [ShawnFeng0/ulog#2]
Hi @shawnfeng0,

Thanks for the amazing tool :)

I was using the [log_rotate](https://github.com/ShawnFeng0/log_rotate.git) program everyday and just found out that you migrated that tool to this repository.

However, the latest [release tag - v0.4.0](https://github.com/shawnfeng0/ulog/releases/tag/v0.4.0) does not seem to include the `log_rotate` tool yet.

May I kindly ask you to create a new tag that contains your latest code since I have a code to manually build it with the latest tag?

Thanks in advance.

**Comment by shawnfeng0** [comment]
Yes, the log_rotate tool has been migrated to ulog. It is now called logrotate, and its command line parameter names are connected by dashes.

Now the logrotate inside ulog is stable and available, and I will release a new version number later. 

Since log_rotate doesn't have any github star/watch/fork, I thought there was no risk in deleting the standalone log_rotate, but sorry to bother you.  

Have you seen the instructions for migrating to ulog internal tools on the readme homepage of log_rotate before?

**Comment by pysan3** [comment]
>  Now the logrotate inside ulog is stable and available, and I will release a new version number later.

Thank you for your quick response! And no worries, I at least had a local copy which auto updates.

> its command line parameter names are connected by dashes.

Ah, I missed this. Thanks for pointing out!

>  Have you seen the instructions for migrating to ulog internal tools on the readme homepage of log_rotate before?

My local README copy says like this. Is this what you meant?

> Please use https://github.com/shawnfeng0/ulog/tree/main/tools/logrotate as an alternative

I am only using the command line interface so I am not really concerned about migrating c code or anything but would be ok if I have the executable.

After cmake and make, The previous `build/log_rotate` is equivalent of `build/tools/logrotate/logrotate` right?

**Comment by shawnfeng0** [comment]
> My local README copy says like this. Is this what you meant?
> 
> > Please use https://github.com/shawnfeng0/ulog/tree/main/tools/logrotate as an alternative

Yes!


> I am only using the command line interface so I am not really concerned about migrating c code or anything but would be ok if I have the executable.
> 
> After cmake and make, The previous `build/log_rotate` is equivalent of `build/tools/logrotate/logrotate` right?

Yes! v0.4.1 has been released, note that the command line parameter names have changed a bit. You can check it with `logrotate --help`.

**Comment by pysan3** [comment]
Thank you so much.

However, I have one problem with `v0.4.1`.

It compiles without any problems on my Arch machine but when I switch to an Ubuntu 20.04 machine, I get `undefined reference to pthread_create` error. [Probably this issue on Stackoverflow](https://stackoverflow.com/questions/1662909/undefined-reference-to-pthread-create-in-linux)

I have no knowledge about c / c++ but I think we need to add `pthread` in the [tools/logrotate/CMakeLists.txt](https://github.com/shawnfeng0/ulog/blob/afa004fa91dddaa38b2896759148e44f11c77dce/tools/logrotate/CMakeLists.txt#L2)? Just like mentioned in `[examples](https://github.com/shawnfeng0/ulog/tree/main/examples)/CMakeLists.txt` ?

at: @shawnfeng0

**Comment by shawnfeng0** [comment]
> It compiles without any problems on my Arch machine but when I switch to an Ubuntu 20.04 machine, I get `undefined reference to pthread_create` error. [Probably this issue on Stackoverflow](https://stackoverflow.com/questions/1662909/undefined-reference-to-pthread-create-in-linux)
> 
> I have no knowledge about c / c++ but I think we need to add `pthread` in the [tools/logrotate/CMakeLists.txt](https://github.com/shawnfeng0/ulog/blob/afa004fa91dddaa38b2896759148e44f11c77dce/tools/logrotate/CMakeLists.txt#L2)? Just like mentioned in `[examples](https://github.com/shawnfeng0/ulog/tree/main/examples)/CMakeLists.txt` ?

Yes, I've added it and urgently released version 0.4.2.
I used to have errors when I used the old version of gcc/clang, but now the gcc/clang on my machine are all up-to-date (Arch Linux), maybe the latest compiler has made some changes, it did not report an error, in order to ensure compatibility I added it.

**Comment by pysan3** [comment]
Thank you so much!

Works like a charm ;)
